version: "3"
services:
  database:
    image: postgres:16-alpine
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: total_tools
      POSTGRES_USER: total_tools
      POSTGRES_PASSWORD: total_tools
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
