mutation CreateNewProject($name: String!) {
  createProject(input:{ name:$name }) {
    project {
      id
    }
  }
}

mutation CreateProyectStep($name: String! $order: Int! $projectId: String!) {
  createProjectStep(input: { projectStep: { name: $name, order: $order, projectId: $projectId } }) {
    projectStep {
      id
    }
  }
}

mutation AddTask(
    $name: String!
    $projectStepId: String!
) {
  createTask(
    input: {
      task: { name: $name description: "" projectStepId: $projectStepId }
    }
  ) {
    clientMutationId
  }
}

mutation UpdateTask($id: String! $description: String!) {
  updateTask(input: { id: $id patch: { description: $description } }) {
    task {
      id
    }
  }
}

mutation DeleteTask($id: String!) {
  deleteTask(input: { id: $id }) {
    task {
      id
    }
  }
}

mutation CreateTaskComment($taskId: String! $comment: String! $userId: String!) {
  createTaskComment(
    input: {
      taskComment: { taskId: $taskId comment: $comment userId: $userId }
    }
  ) {
    taskComment {
      id
    }
  }
}
