query GetProjects {
  projects {
    nodes {
      id
      name
    }
  }
}

query GetProjectById($id: String!) {
  projects(filter: {id: { equalTo: $id } }, first: 1) {
    nodes {
      id
      name
    }
  }
}

query GetProyectSteps($projectId: String!) {
  projectSteps(filter: { projectId: { equalTo: $projectId } }) {
    nodes {
      id
      name
      order
    }
  }
}

query GetTasksByProjectStepId($projectStepId: String!) {
  tasks(filter: { projectStepId: { equalTo: $projectStepId } }) {
    nodes {
      id
      name
      description
      userId
    }
  }
}

query GetTasksComments($taskId: String!) {
  taskComments(filter: { taskId: { equalTo: $taskId } } orderBy: CREATED_AT_DESC) {
    nodes {
      id
      comment
      createdAt
      user {
        id
        accountId
        name
        familyName
        email
      }
    }
  }
}

query WhoAmI($accountId: String!){
  whoAmI(accountId: $accountId) {
    id
    name
    familyName
    email
    cellphone
  }
}
